version: '2.2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todolist-db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3309:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/dental-mysql
volumes:
  my-db:
    driver: local